import type { Metadata } from 'next'
import './globals.css'
// import { Geist, Geist_Mono } from "next/font/google";

import './globals.css'
import ReactQuery from '@/components/reactQuery'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  )
}
