import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from "next/font/google";

import './globals.css'
import ReactQuery from '@/components/reactQuery'
import { Poppins } from 'next/font/google'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased ${poppins.className} bg-gray-100 text-gray-900`}>
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  )
}
