import type { Metadata } from 'next'
import './globals.css'
// import { Geist, Geist_Mono } from "next/font/google";

import './globals.css'
import ReactQuery from '@/components/reactQuery'
import { Session } from 'next-auth'
import NextAuthProvider from '@/components/NextAuthProvider'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  session: Session | null | undefined
}) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
          <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  )
}
